{{- if or .Values.feSpec.configMap .Values.beSpec.configMap .Values.cnSpec.configMap .Values.brokerSpec.configMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "doriscluster.default.configMap.name" . }}
  namespace: {{ template "doriscluster.namespace" . }}
  labels:
    app.kubernetes.io/name: doriscluster
    app.kubernetes.io/instance: {{ template "doriscluster.name" . }}
    app.kubernetes.io/part-of: {{ template "kube-control.name" . }}
data:
  {{- $configMap := dict }}

  {{- if .Values.feSpec.configMap}}
  {{- $configMap = merge $configMap .Values.feSpec.configMap }}
  {{- end }}

  {{- if .Values.beSpec.configMap}}
  {{- $configMap = merge $configMap .Values.beSpec.configMap }}
  {{- end }}

  {{- if .Values.cnSpec.configMap}}
  {{- $configMap = merge $configMap .Values.cnSpec.configMap }}
  {{- end }}

  {{- if .Values.brokerSpec.configMap}}
  {{- $configMap = merge $configMap .Values.brokerSpec.configMap }}
  {{- end }}

  {{- toYaml $configMap | nindent 2}}

{{- end }}
