{{- if .Values.beSpec.configMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "doriscluster.default.beConfigMap.name" . }}
  namespace: {{ template "doriscluster.namespace" . }}
  labels:
    app.kubernetes.io/name: doriscluster
    app.kubernetes.io/instance: {{ template "doriscluster.name" . }}
    app.kubernetes.io/part-of: {{ template "kube-control.name" . }}
data:
  {{- toYaml .Values.beSpec.configMap | nindent 2 }}
{{- end }}
