apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: service
    app.kubernetes.io/instance: webhook-service
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: doris-operator
    app.kubernetes.io/part-of: doris-operator
    app.kubernetes.io/managed-by: kustomize
  name: webhook-service
  namespace: doris
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    control-plane: doris-operator
    app.kubernetes.io/component: doris-operator
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
      - v1alpha1
    clientConfig:
      service:
        name: webhook-service
        namespace: doris
        path: /validate-doris-selectdb-com-v1-doriscluster
    failurePolicy: Ignore
    matchPolicy: Exact
    name: doriscluster.selectdb.com
    rules:
      - apiGroups:
          - doris.selectdb.com
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - doriscluster
    sideEffects: None