# This yaml have autoscaler config in contrast to `doriscluster-sample-cn.yaml`, the details usage can reference [doc](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/)
apiVersion: doris.selectdb.com/v1
kind: DorisCluster
metadata:
  labels:
    app.kubernetes.io/name: doriscluster
    app.kubernetes.io/instance: doriscluster-sample-cn
    app.kubernetes.io/part-of: doris-operator
  name: doriscluster-sample
spec:
  feSpec:
    replicas: 3
    image: selectdb/doris.fe-ubuntu:2.0.2
  cnSpec:
    replicas: 3
    # cn used be image, doris use config file to start compute. set the field ` be_node_role = computation` in be.conf to start be as compute.
    # and config cn use configmap to effect config
    configMapInfo:
      # use kubectl create configmap cn-configmap --from-file=be.conf
      configMapName: cn-configmap
      resolveKey: be.conf
    image: selectdb/doris.be-ubuntu:2.0.2
    autoScalingPolicy:
      # version have two values:v2,v1 response horizontalPodAutoscaler v1 and v2 versions.
      version: "v2"
      minReplicas: 2
      maxReplicas: 10
      # hpaPolicy response to horizontlaPodAutoscaler's HorizontalPodAutoscalerSpec
      hpaPolicy:
        metrics:
          - type: Resource
            resource:
              name: cpu
              target:
                type: Utilization
                averageUtilization: 30