# This yaml describe have to deploy fe as observer. Its base yaml is `doriscluster-sample.yaml`.
apiVersion: doris.selectdb.com/v1
kind: DorisCluster
metadata:
  labels:
    app.kubernetes.io/name: doriscluster
    app.kubernetes.io/instance: doriscluster-sample
    app.kubernetes.io/part-of: doris-operator
  name: doriscluster-sample
spec:
  feSpec:
    # the electionNumber represents the number of FOLLOWER, (replicas - electionNumber) represents the number of OBSERVER.
    # the replicas must greater than replicas.
    electionNumber: 3
    replicas: 5
    image: selectdb/doris.fe-ubuntu:2.1.1
    limits:
      cpu: 8
      memory: 16Gi
    requests:
      cpu: 8
      memory: 16Gi
  beSpec:
    replicas: 3
    image: selectdb/doris.be-ubuntu:2.1.1
    limits:
      cpu: 8
      memory: 16Gi
    requests:
      cpu: 8
      memory: 16Gi
