apiVersion: doris.selectdb.com/v1
kind: DorisCluster
metadata:
  labels:
    app.kubernetes.io/name: doriscluster
    app.kubernetes.io/instance: doriscluster-sample
    app.kubernetes.io/part-of: doris-operator
  name: doriscluster-sample
  namespace: doris
spec:
  feSpec:
    # the electionNumber represents the number of FOLLOWER, (replicas - electionNumber) represents the number of OBSERVER.
    # the replicas must greater than replicas.
    electionNumber: 3
    replicas: 5
    image: selectdb.doris.fe:v1.3
  beSpec:
    replicas: 3
    image: 10.16.10.8:32000/selectdb.doris.be:v1.8