# permissions for end users to edit dorisclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: doriscluster-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: doris-operator
    app.kubernetes.io/part-of: doris-operator
    app.kubernetes.io/managed-by: kustomize
  name: doriscluster-editor-role
rules:
- apiGroups:
  - doris.selectdb.com
  resources:
  - dorisclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - doris.selectdb.com
  resources:
  - dorisclusters/status
  verbs:
  - get
