# Default values for operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

dorisOperator:
  namespaceOverride: "doris"
  image:
    repository: selectdb/doris.k8s-operator
    tag: latest
  resources:
    cpu: "2"
    memory: 4Gi
