{{ $namespacefind := (lookup "v1" "Namespace" "" (printf ( include "operator.namespace" .))) }}
{{ if not $namespacefind }}
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    control-plane: {{ template "kube-doris.name" . }}-operator
    app.kubernetes.io/name: namespace
    app.kubernetes.io/instance: {{ template "kube-doris.name" . }}
    app.kubernetes.io/component: {{ template "kube-doris.name" . }}-operator
    app.kubernetes.io/part-of: {{ template "kube-doris.name" . }}-operator
  name: {{ template "operator.namespace"  . }}
{{ end }}