apiVersion: v1
entries:
  doris:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-11-01T15:07:29.212629+08:00"
    description: A Helm chart for Apache Doris cluster
    digest: 73270764d771b271e763d5ecb358e56de0739d9aff16aaa26d4109379d642b99
    name: doris
    type: application
    urls:
    - doris-0.1.0.tgz
    version: 0.1.0
  operator:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-11-01T15:07:29.214011+08:00"
    description: A Helm chart for Apache Doris Kubernetes Operator
    digest: 1d0811fead80ab263a2b224864a13255652ee905d629d093fd4d7a451e9dba30
    name: operator
    type: application
    urls:
    - operator-0.1.0.tgz
    version: 0.1.0
generated: "2023-11-01T15:07:29.211575+08:00"
